### PR TITLE
Fix treeview

### PR DESCRIPTION
**Pull request by Protryon**
Forked treeview-ui, released new package with Polymer 3.0 support and fixed graphical issues.

### CODE REVIEW

**Comment by michaelficarra** [comment]
I'm unable to run this demo locally. I get the error

> TypeError: output.display is not a function

in the console.

**Comment by Protryon** [comment]
@michaelficarra Do a `npm i`, as this includes the `ui-treeview` library via node.

**Comment by michaelficarra** [comment]
@Protryon I did.

**Comment by Protryon** [comment]
@michaelficarra Ready for review/merge.

**Review by michaelficarra — APPROVED** [review]

**Pull request merged**
